'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { apiFetch } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { useToast } from '@/lib/toast-context';

interface VoucherItem {
  id: number;
  voucherNumber: string;
  status: 'unpaid' | 'paid';
  courseFee: number;
  previousDue: number;
  totalAmount: number;
  dueDate: string | null;
  createdAt: string;
  lineItems: Array<{
    courseId: number;
    courseTitle: string;
    coursePrice: number;
  }>;
}

export default function StudentFeeVouchersPage() {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const toast = useToast();

  const [vouchers, setVouchers] = useState<VoucherItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authLoading && (!user || user.role !== 'student')) {
      router.replace('/dashboard');
      return;
    }

    if (user) {
      apiFetch('/fee-vouchers/my')
        .then(setVouchers)
        .catch(() => toast.error('Failed to load your fee vouchers'))
        .finally(() => setLoading(false));
    }
  }, [user, authLoading, router, toast]);

  const handleDownload = async (voucherId: number) => {
    try {
      const voucher = await apiFetch(`/fee-vouchers/my/${voucherId}/download`);
      const html = `
        <html>
          <head>
            <title>Fee Voucher ${voucher.voucherNumber}</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 24px; color: #111; }
              .card { border: 1px solid #ddd; border-radius: 12px; padding: 20px; max-width: 720px; }
              h1 { margin: 0 0 8px; }
              table { width: 100%; border-collapse: collapse; margin-top: 16px; }
              td { padding: 8px 4px; border-bottom: 1px solid #eee; }
              td:last-child { text-align: right; }
            </style>
          </head>
          <body>
            <div class="card">
              <h1>Fee Voucher</h1>
              <p><strong>Voucher #:</strong> ${voucher.voucherNumber}</p>
              <p><strong>Type:</strong> Consolidated Student Voucher</p>
              <p><strong>Status:</strong> ${voucher.status}</p>
              <p><strong>Due Date:</strong> ${voucher.dueDate ? new Date(voucher.dueDate).toLocaleDateString() : '-'}</p>
              <table>
                ${voucher.lineItems.length > 0
                  ? voucher.lineItems
                      .map(
                        (item: { courseTitle: string; coursePrice: number }) =>
                          `<tr><td>${item.courseTitle}</td><td>${Number(item.coursePrice).toFixed(2)}</td></tr>`,
                      )
                      .join('')
                  : '<tr><td>No active course dues</td><td>0.00</td></tr>'}
                <tr><td>Course Fee</td><td>${Number(voucher.courseFee).toFixed(2)}</td></tr>
                <tr><td>Previous Unpaid Dues</td><td>${Number(voucher.previousDue).toFixed(2)}</td></tr>
                <tr><td><strong>Total Payable</strong></td><td><strong>${Number(voucher.totalAmount).toFixed(2)}</strong></td></tr>
              </table>
              <p style="margin-top:16px;font-size:12px;color:#444;">This voucher is generated by UniPortal and payment status is verified by admin only.</p>
            </div>
          </body>
        </html>
      `;

      const popup = window.open('', '_blank');
      if (!popup) {
        throw new Error('Unable to open print window');
      }
      popup.document.write(html);
      popup.document.close();
      popup.focus();
      popup.print();
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : 'Failed to download voucher');
    }
  };

  if (authLoading || loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-zinc-300 border-t-zinc-900 dark:border-zinc-700 dark:border-t-white" />
      </div>
    );
  }

  if (!user || user.role !== 'student') return null;

  return (
    <div className="max-w-5xl mx-auto px-6 py-8 space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-zinc-900 dark:text-white">My Fee Vouchers</h1>
        <p className="text-zinc-500 dark:text-zinc-400 mt-1">
          Download your vouchers. Course access is blocked until corresponding voucher is marked paid by admin.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        {vouchers.map((v) => (
          <div key={v.id} className="bg-white dark:bg-zinc-900 rounded-xl border border-zinc-200 dark:border-zinc-800 p-5">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-xs font-mono text-zinc-500">{v.voucherNumber}</p>
                <h2 className="text-lg font-semibold text-zinc-900 dark:text-white mt-1">Consolidated Voucher</h2>
                <p className="text-sm text-zinc-500 dark:text-zinc-400">Accumulated dues from registered courses</p>
              </div>
              <span
                className={`text-xs px-2.5 py-1 rounded-full ${
                  v.status === 'paid'
                    ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400'
                    : 'bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-400'
                }`}
              >
                {v.status}
              </span>
            </div>

            <div className="mt-4 text-sm space-y-1 text-zinc-600 dark:text-zinc-300">
              <div className="rounded-lg border border-zinc-200 dark:border-zinc-800 overflow-hidden">
                <div className="px-3 py-2 bg-zinc-50 dark:bg-zinc-800/60 font-medium text-zinc-700 dark:text-zinc-200">
                  Course Details
                </div>
                <div className="divide-y divide-zinc-100 dark:divide-zinc-800">
                  {v.lineItems.length > 0 ? v.lineItems.map((item) => (
                    <div key={item.courseId} className="flex items-center justify-between px-3 py-2">
                      <span>{item.courseTitle}</span>
                      <span className="font-medium">{Number(item.coursePrice).toFixed(2)}</span>
                    </div>
                  )) : (
                    <div className="px-3 py-2 text-zinc-500 dark:text-zinc-400">
                      No active course dues
                    </div>
                  )}
                </div>
              </div>
              <p>Course Fee: <span className="font-medium">{Number(v.courseFee).toFixed(2)}</span></p>
              <p>Previous Dues: <span className="font-medium">{Number(v.previousDue).toFixed(2)}</span></p>
              <p>Total: <span className="font-semibold">{Number(v.totalAmount).toFixed(2)}</span></p>
              <p>Due Date: <span className="font-medium">{v.dueDate ? new Date(v.dueDate).toLocaleDateString() : '-'}</span></p>
            </div>

            <button
              onClick={() => handleDownload(v.id)}
              className="mt-4 w-full text-sm px-4 py-2.5 rounded-lg bg-gradient-to-r from-indigo-500 to-violet-500 text-white hover:opacity-95 transition-opacity cursor-pointer"
            >
              Download / Print Voucher
            </button>
          </div>
        ))}
      </div>

      {vouchers.length === 0 && (
        <div className="bg-white dark:bg-zinc-900 rounded-xl border border-zinc-200 dark:border-zinc-800 p-8 text-center text-zinc-500 dark:text-zinc-400">
          No vouchers generated yet. Contact admin if you have registered courses.
        </div>
      )}
    </div>
  );
}
